import { db } from '@/db';
import { missingPersons } from '@/db/schema';

async function main() {
    // Delete existing records
    await db.delete(missingPersons);

    const sampleMissingPersons = [
        {
            reportedBy: 1,
            fullName: 'Emma Rodriguez',
            age: 5,
            gender: 'Female',
            height: '4\'5"',
            weight: '60 lbs',
            hairColor: 'Brown',
            eyeColor: 'Brown',
            complexion: 'Medium',
            distinguishingMarks: 'Dimples on both cheeks',
            lastSeenLocation: 'Central Park NYC',
            lastSeenDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Last seen wearing pink dress and white sneakers. Was playing near the playground.',
            status: 'active',
            contactInfo: '+1-555-1001',
            createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 2,
            fullName: 'Marcus Thompson',
            age: 12,
            gender: 'Male',
            height: '5\'2"',
            weight: '120 lbs',
            hairColor: 'Black',
            eyeColor: 'Brown',
            complexion: 'Dark',
            distinguishingMarks: 'Scar above right eyebrow',
            lastSeenLocation: 'Times Square New York',
            lastSeenDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Was heading to school when disappeared. Wearing school uniform with blue backpack.',
            status: 'active',
            contactInfo: '+1-555-1002',
            createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 3,
            fullName: 'Lily Chen',
            age: 16,
            gender: 'Female',
            height: '5\'4"',
            weight: '125 lbs',
            hairColor: 'Black',
            eyeColor: 'Brown',
            complexion: 'Light Brown',
            distinguishingMarks: 'Pierced nose',
            lastSeenLocation: 'Brooklyn Bridge Park',
            lastSeenDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Last seen wearing blue jeans and red jacket. Was meeting friends after school.',
            status: 'found',
            contactInfo: '+1-555-1003',
            createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 4,
            fullName: 'James Anderson',
            age: 22,
            gender: 'Male',
            height: '6\'1"',
            weight: '190 lbs',
            hairColor: 'Blonde',
            eyeColor: 'Blue',
            complexion: 'Fair',
            distinguishingMarks: 'Tattoo of anchor on right shoulder',
            lastSeenLocation: 'Miami Beach Florida',
            lastSeenDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Left for morning jog and never returned. Wearing gray athletic gear.',
            status: 'active',
            contactInfo: '+1-555-1004',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 5,
            fullName: 'Sofia Martinez',
            age: 28,
            gender: 'Female',
            height: '5\'5"',
            weight: '135 lbs',
            hairColor: 'Brown',
            eyeColor: 'Hazel',
            complexion: 'Olive',
            distinguishingMarks: 'Birthmark on neck',
            lastSeenLocation: 'Los Angeles Downtown',
            lastSeenDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Left home for grocery shopping and never returned. Wearing black pants and white blouse.',
            status: 'active',
            contactInfo: '+1-555-1005',
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 6,
            fullName: 'Tyler Johnson',
            age: 35,
            gender: 'Male',
            height: '5\'11"',
            weight: '180 lbs',
            hairColor: 'Light Brown',
            eyeColor: 'Green',
            complexion: 'Medium',
            distinguishingMarks: 'Tattoo of rose on left arm',
            lastSeenLocation: 'Chicago Loop District',
            lastSeenDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Was on his way to work conference. Last seen wearing business suit and carrying briefcase.',
            status: 'closed',
            contactInfo: '+1-555-1006',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 7,
            fullName: 'Olivia Williams',
            age: 42,
            gender: 'Female',
            height: '5\'6"',
            weight: '140 lbs',
            hairColor: 'Auburn',
            eyeColor: 'Blue',
            complexion: 'Fair',
            distinguishingMarks: 'Mole on right cheek',
            lastSeenLocation: 'Boston Common Park',
            lastSeenDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Went for evening walk with her dog. Dog returned home alone hours later.',
            status: 'active',
            contactInfo: '+1-555-1007',
            createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 1,
            fullName: 'Ethan Davis',
            age: 48,
            gender: 'Male',
            height: '6\'3"',
            weight: '210 lbs',
            hairColor: 'Salt and Pepper',
            eyeColor: 'Gray',
            complexion: 'Fair',
            distinguishingMarks: 'Burn scar on left hand',
            lastSeenLocation: 'Seattle Waterfront',
            lastSeenDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Left for fishing trip early morning. Boat was found empty later that day.',
            status: 'active',
            contactInfo: '+1-555-1008',
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 2,
            fullName: 'Ava Garcia',
            age: 55,
            gender: 'Female',
            height: '5\'3"',
            weight: '130 lbs',
            hairColor: 'Gray',
            eyeColor: 'Brown',
            complexion: 'Medium',
            distinguishingMarks: 'Freckles across nose',
            lastSeenLocation: 'Portland Downtown Oregon',
            lastSeenDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Was attending yoga class. Never arrived and car was found abandoned nearby.',
            status: 'found',
            contactInfo: '+1-555-1009',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 3,
            fullName: 'Noah Miller',
            age: 62,
            gender: 'Male',
            height: '5\'9"',
            weight: '170 lbs',
            hairColor: 'Gray',
            eyeColor: 'Blue',
            complexion: 'Fair',
            distinguishingMarks: 'Missing front tooth',
            lastSeenLocation: 'Austin Downtown Texas',
            lastSeenDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Left retirement home for daily walk. Did not return for dinner time.',
            status: 'active',
            contactInfo: '+1-555-1010',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 4,
            fullName: 'Isabella Wilson',
            age: 67,
            gender: 'Female',
            height: '5\'4"',
            weight: '125 lbs',
            hairColor: 'Gray',
            eyeColor: 'Hazel',
            complexion: 'Fair',
            distinguishingMarks: 'Glasses with black frames',
            lastSeenLocation: 'Denver City Center',
            lastSeenDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Went to library as usual. Library staff noticed she left her belongings behind.',
            status: 'active',
            contactInfo: '+1-555-1011',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 5,
            fullName: 'Mason Moore',
            age: 73,
            gender: 'Male',
            height: '5\'7"',
            weight: '155 lbs',
            hairColor: 'Gray',
            eyeColor: 'Blue',
            complexion: 'Fair',
            distinguishingMarks: 'Scar on left knee',
            lastSeenLocation: 'Philadelphia Historic District',
            lastSeenDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Was on guided tour of historic sites. Group noticed he was missing during headcount.',
            status: 'active',
            contactInfo: '+1-555-1012',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 6,
            fullName: 'Mia Taylor',
            age: 19,
            gender: 'Female',
            height: '5\'8"',
            weight: '165 lbs',
            hairColor: 'Blonde',
            eyeColor: 'Blue',
            complexion: 'Fair',
            distinguishingMarks: 'Tattoo of butterfly on ankle',
            lastSeenLocation: 'San Francisco Golden Gate',
            lastSeenDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'College student who went hiking alone. Her car was found in parking lot three days later.',
            status: 'found',
            contactInfo: '+1-555-1013',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 7,
            fullName: 'Lucas Anderson',
            age: 31,
            gender: 'Male',
            height: '6\'0"',
            weight: '200 lbs',
            hairColor: 'Dark Brown',
            eyeColor: 'Green',
            complexion: 'Medium',
            distinguishingMarks: 'Tattoo of dragon on back',
            lastSeenLocation: 'Las Vegas Strip',
            lastSeenDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Was attending bachelor party. Friends last saw him leaving casino around midnight.',
            status: 'active',
            contactInfo: '+1-555-1014',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            reportedBy: 1,
            fullName: 'Charlotte Brown',
            age: 80,
            gender: 'Female',
            height: '4\'10"',
            weight: '80 lbs',
            hairColor: 'Gray',
            eyeColor: 'Brown',
            complexion: 'Fair',
            distinguishingMarks: 'Braces on teeth',
            lastSeenLocation: 'Phoenix Downtown',
            lastSeenDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            description: 'Left assisted living facility. Staff noticed her absence during evening medication rounds.',
            status: 'closed',
            contactInfo: '+1-555-1015',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(missingPersons).values(sampleMissingPersons);
    
    console.log('✅ Missing persons seeder completed successfully - 15 reports created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});